### ISSUE TITLE
error with photo_upload_to_story

### ISSUE THREAD

**Issue by aeris07** [subzeroid/instagrapi#1586]
Hello, 
I was using photo_upload_to_story function for uploading a photo  and create a new story with a location at my instagram account

Relevant piece of code is below:

                photos = random.choice(os.listdir(photo_path))
                photo_list = [f"{photo_path}/{photo}" for photo in photos]
                answer= bot.photo_upload_to_story(path=photos,
                                                  locations=Location(external_id=location_external_id, name=location_name))

**Error I got is as below:**

raceback (most recent call last):
  File "C:\Users\MyPC\PycharmProjects\pythonProject\venv\Lib\site-packages\instagrapi\mixins\private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "C:\Users\MyPC\PycharmProjects\pythonProject\venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\MyPC\PycharmProjects\pythonProject\amazingo.py", line 88, in login_and_story
    bot.login(username, password)
  File "C:\Users\MyPC\PycharmProjects\pythonProject\venv\Lib\site-packages\instagrapi\mixins\auth.py", line 441, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyPC\PycharmProjects\pythonProject\venv\Lib\site-packages\instagrapi\mixins\private.py", line 542, in private_request
    raise e
  File "C:\Users\MyPC\PycharmProjects\pythonProject\venv\Lib\site-packages\instagrapi\mixins\private.py", line 527, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\MyPC\PycharmProjects\pythonProject\venv\Lib\site-packages\instagrapi\mixins\private.py", line 383, in _send_private_request
    raise PleaseWaitFewMinutes(e, response=e.response, **last_json)
instagrapi.exceptions.PleaseWaitFewMinutes: Please wait a few minutes before you try again.

Enironment
 - OS: Windows
 - Python version [3.11.0]
 - instagrapi version [2.25.1]

I couldn't figure out what is the exact reason of this error.

**Comment by subzeroid** [comment]
The traceback fails during `bot.login(...)` with `PleaseWaitFewMinutes`, before `photo_upload_to_story(...)` is reached. That is Instagram rate/account-risk enforcement on login, not a story-upload bug.

Current guidance:

- Best practices: https://subzeroid.github.io/instagrapi/usage-guide/best-practices
- Session reuse/settings: https://github.com/subzeroid/instagrapi#session-persistence

Closing this as misattributed/stale. A story-upload bug should include a traceback from `photo_upload_to_story` or the configure/upload endpoint on a current release.

**Comment by subzeroid** [comment]
Closed as login rate/account-risk error, not a photo_upload_to_story defect.
