### ISSUE TITLE
medias = cl.hashtag_medias_recent('downhill', amount=2) [BUG]

### ISSUE THREAD

**Issue by TimoZuerner** [subzeroid/instagrapi#1591]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

Getting a Key Error when trying a function for Hashtags

`
medias = cl.hashtag_medias_a1(name='test', amount=40, tab_key="recent")
`

Error:  Traceback (most recent call last):
  File "....\main.py", line 59, in <module>
    medias = cl.hashtag_medias_a1(name='test', amount=40, tab_key="recent")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....\venv\Lib\site-packages\instagrapi\mixins\hashtag.py", line 222, in hashtag_medias_a1
    medias, _ = self.hashtag_medias_a1_chunk(name, amount, tab_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....\venv\Lib\site-packages\instagrapi\mixins\hashtag.py", line 179, in hashtag_medias_a1_chunk
    result = data["data"][tab_key]
             ~~~~^^^^^^^^
KeyError: 'data'

**Desktop :**
 - OS: Windows
 - Python version 3.11
 - instagrapi version: grapi-0.1.4


**Additional context**
Also key error with this code:
`medias = cl.hashtag_medias_recent('downhill', amount=2)`

**Comment by blackaquaindia** [comment]
i got this same error since last day i checked it
its not working
medias = cl.hashtag_medias_recent('downhill', amount=2)

**Comment by BourhaneYounes** [comment]
It's the same with hashtag_medias_top(), the other methods work fine but these two keep giving a "Key error"

**Comment by subzeroid** [comment]
Verified on current `master` / `instagrapi 2.8.18`: `cl.hashtag_medias_recent("downhill", amount=2)`, `cl.hashtag_medias_top("downhill", amount=2)`, and two-page `cl.hashtag_medias_v1_chunk("downhill", tab_key="recent")` all return `Media` objects without the old `KeyError: data`.

The old `hashtag_medias_a1*` helpers were removed with the dead public `?__a=1` API surface; use `hashtag_medias_recent(...)` / `hashtag_medias_top(...)` or the private `*_v1` helpers instead. The hashtag sections fix was released in https://github.com/subzeroid/instagrapi/releases/tag/2.8.18. Closing this as fixed.
