### ISSUE TITLE
[BUG] How to resolve this type of challenge?

### ISSUE THREAD

**Issue by funnyruler** [subzeroid/instagrapi#1619]
Have an unexpected type of challenge - checkbox on instagram page. Got this challenge while scrapping user profiles by `client.user_info(user_pk)`

Traceback
```
public.py [ LINE:160] INFO     [2023-10-16 23:09:53,972] [None] [401] GET https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%22262927956%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
connectionpool.py [ LINE:546] DEBUG    [2023-10-16 23:09:57,101] https://www.instagram.com:443 "GET /graphql/query/?variables=%7B%22user_id%22%3A%22262927956%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7 HTTP/1.1" 401 98
    public.py [ LINE:156] DEBUG    [2023-10-16 23:09:57,102] public_request 401: https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%22262927956%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
    public.py [ LINE:160] INFO     [2023-10-16 23:09:57,102] [None] [401] GET https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%22262927956%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7
   private.py [ LINE:329] INFO     [2023-10-16 23:09:58,102] https://i.instagram.com/api/v1/users/262927956/info/
connectionpool.py [ LINE:546] DEBUG    [2023-10-16 23:09:58,261] https://i.instagram.com:443 "GET /api/v1/users/262927956/info/ HTTP/1.1" 400 259
   private.py [ LINE:349] DEBUG    [2023-10-16 23:09:58,262] private_request 400: https://i.instagram.com/api/v1/users/262927956/info/ ({"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/?next=/api/v1/users/262927956/info/","api_path":"/challenge/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail"})
   private.py [ LINE:485] INFO     [2023-10-16 23:09:58,262] myprofile [400] GET https://i.instagram.com/api/v1/users/262927956/info/ (269.0.0.18.75, OnePlus 6T Dev)
   private.py [ LINE:329] INFO     [2023-10-16 23:09:59,262] https://i.instagram.com/api/v1/challenge/
connectionpool.py [ LINE:546] DEBUG    [2023-10-16 23:09:59,738] https://i.instagram.com:443 "GET /api/v1/challenge/ HTTP/1.1" 400 224
   private.py [ LINE:349] DEBUG    [2023-10-16 23:09:59,739] private_request 400: https://i.instagram.com/api/v1/challenge/ ({"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/","api_path":"/challenge/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":4},"status":"fail"})
   private.py [ LINE:485] INFO     [2023-10-16 23:09:59,739] myprofile [400] GET https://i.instagram.com/api/v1/challenge/ (269.0.0.18.75, OnePlus 6T Dev)
connectionpool.py [ LINE:1048] DEBUG    [2023-10-16 23:10:04,741] Starting new HTTPS connection (1): i.instagram.com:443
connectionpool.py [ LINE:546] DEBUG    [2023-10-16 23:10:04,919] https://i.instagram.com:443 "GET /challenge/ HTTP/1.1" 200 77
connectionpool.py [ LINE:546] DEBUG    [2023-10-16 23:10:10,007] https://i.instagram.com:443 "POST /challenge/ HTTP/1.1" 200 90
   private.py [ LINE:329] INFO     [2023-10-16 23:10:16,009] https://i.instagram.com/api/v1/users/262927956/info/
connectionpool.py [ LINE:546] DEBUG    [2023-10-16 23:10:16,164] https://i.instagram.com:443 "GET /api/v1/users/262927956/info/ HTTP/1.1" 400 259
   private.py [ LINE:349] DEBUG    [2023-10-16 23:10:16,165] private_request 400: https://i.instagram.com/api/v1/users/262927956/info/ ({"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/?next=/api/v1/users/262927956/info/","api_path":"/challenge/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail"})
   private.py [ LINE:485] INFO     [2023-10-16 23:10:16,165] myprofile [400] GET https://i.instagram.com/api/v1/users/262927956/info/ (269.0.0.18.75, OnePlus 6T Dev)
base_events.py [ LINE:1753] ERROR    [2023-10-16 23:10:16,165] Task exception was never retrieved
future: <Task finished name='Task-16' coro=<Dispatcher._process_polling_updates() done, defined at C:\code\1_fl\insta_scrapper_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=ChallengeRequired('challenge_required')>
Traceback (most recent call last):
  File "C:\code\1_fl\insta_scrapper_bot\venv\lib\site-packages\instagrapi\mixins\public.py", line 168, in _send_public_request
    response.raise_for_status()
  File "C:\code\1_fl\insta_scrapper_bot\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.instagram.com/graphql/query/?variables=%7B%22user_id%22%3A%22262927956%22%2C%22include_reel%22%3Atrue%7D&query_hash=ad99dd9d3646cc3c0dda65debcd266a7

```

**Screenshots**
![image](https://github.com/subzeroid/instagrapi/assets/52204590/7bbb5560-08dc-4280-ae4c-b48da2beebc6)

 - OS: Win 10 x64
 - Python 3.9
 - instagrapi==2.0.0

How can i solve this?

**Comment by jtarun4625** [comment]
Any Update on this bug how to resolve this ?

**Comment by igklcs** [comment]
> Any Update on this bug how to resolve this ?

It is not bug you need to a captcha solver.

**Comment by subzeroid** [comment]
This is an account challenge/checkpoint flow, not a normal API response bug. The reported payload is `checkpoint_required` / `challenge_required` with a checkbox-style challenge from Instagram. Those flows are account/device/trust dependent and may require manual confirmation or a captcha/checkpoint solver; they are not reliably bypassable by a generic library method.

Current docs:

- Challenge resolver: https://subzeroid.github.io/instagrapi/usage-guide/challenge_resolver
- Best practices: https://subzeroid.github.io/instagrapi/usage-guide/best-practices

If a current `instagrapi >= 2.9.1` response exposes a specific unsupported `step_name`, `challengeType`, or `bloks_action` that should be represented by a typed exception, please open a new focused issue with the sanitized `last_json`.

Closing this old report because the posted case is a platform checkpoint, not a reproducible library defect.

**Comment by subzeroid** [comment]
Closed as platform checkpoint/account challenge, not a reproducible instagrapi defect.
