### ISSUE TITLE
I can't send any DM to anyone other than myself (Max retries exceeded with url: /api/v1/direct_v2/threads/broadcast/text/ (Caused by ResponseError('too many 500 error responses')))

### ISSUE THREAD

**Issue by spacehitchiker** [subzeroid/instagrapi#1622]
I'm trying to send DMs but it gives error whenever I try to send DM to someone other than myself.

For example something simple as:

`from instagrapi import Client

cl = Client()
cl.load_settings('session_chiyo.json')
threads = cl.direct_threads(1)
user_id = threads[0].id
cl.direct_send("hi there", [int(user_id)])
`

**Error:**

`urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 941, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 941, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 941, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 931, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/direct_v2/threads/broadcast/text/ (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Feza\Documents\pythonProject\deftry.py", line 7, in <module>
    cl.direct_send("hi there", [int(user_id)])
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\instagrapi\mixins\direct.py", line 454, in direct_send
    result = self.private_request(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\instagrapi\mixins\private.py", line 542, in private_request
    raise e
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\instagrapi\mixins\private.py", line 527, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\instagrapi\mixins\private.py", line 341, in _send_private_request
    response = self.private.post(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Feza\Documents\pythonProject\venv\Lib\site-packages\requests\adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/direct_v2/threads/broadcast/text/ (Caused by ResponseError('too many 500 error responses'))
`

**Comment by xts-bit** [comment]
@subzeroid This is an issue with this library. Unfortunately, it's tough to reproduce it because it comes randomly, in my case it comes when I run my code 8-10 times in 5-10 mins. 

Will this be fixed?

**Comment by spacehitchiker** [comment]
> @subzeroid This is an issue with this library. Unfortunately, it's tough to reproduce it because it comes randomly, in my case it comes when I run my code 8-10 times in 5-10 mins.
> 
> Will this be fixed?

I wish I could even run my code that much without problem, I get this error all the time, do you use a proxy?

**Comment by xts-bit** [comment]
@spacehitchiker No, I also get that same error @subzeroid Any fix?

**Comment by diegoterron** [comment]
still happening, i can't send any dms at this point

**Comment by zcabbub** [comment]
still no DM working

**Comment by thegreatref** [comment]
🛠️ Instagram Max Retries Issue: SSLError on video_upload_to_story
❗ Problem

While uploading Instagram stories using the [instagrapi](https://github.com/adw0rd/instagrapi) Python library, I encountered the following error:

requests.exceptions.SSLError: HTTPSConnectionPool(host='i.instagram.com', port=443):

Max retries exceeded with url: /rupload_igvideo/...
(Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2406)')))

This error occurred during the video_upload_to_story() method when trying to upload a story reel with a caption and swipe-up link.
🔍 Diagnosis

After several retries and debugging steps, I realized this issue was not caused by the code or a library bug, but rather by network-related SSL/TLS restrictions — specifically:

Instagram blocking requests based on my IP or DNS
Inconsistent SSL handshake due to ISP-level filtering
Possibly Instagram throttling bot-like behavior on public/home networks

✅ Solution

I solved this issue by connecting to a VPN, which changed my network route and IP. After doing this, the exact same script ran successfully without any modifications.
✅ Recommendations

If you're running into similar SSL or EOF errors when uploading videos:

Try connecting to a VPN
    Especially if you’re on a public network, behind a firewall, or using an ISP known to filter traffic.

Keep your libraries updated

pip install --upgrade instagrapi requests certifi

Avoid repeated retries on SSL errors
    If SSL fails once due to a blocked IP, retrying from the same connection won’t help.
    Add conditional logic to handle this gracefully.

Automatically switch to a proxy

📦 Optional: Add SSL Health Check Before Upload

Here’s a quick method to verify SSL access before attempting uploads:

import requests

def instagram_ssl_ok():
try:
r = requests.get("https://i.instagram.com/", timeout=5)
return r.status_code == 200
except requests.exceptions.SSLError:
return False

💬 Final Thoughts

This issue was a great reminder that automation scripts involving real platforms (like Instagram) need to account for external factors like:

Network filtering
SSL/TLS compatibility
IP-based rate-limiting or blocking

Handling these gracefully can save you hours of debugging and retries.

Let me know if this helps

**Comment by subzeroid** [comment]
Closing this old Direct send report as a usage issue in the provided repro.

The sample uses threads[0].id as a user id:

    user_id = threads[0].id
    cl.direct_send('hi there', [int(user_id)])

But thread ids and user ids are different identifiers. For an existing thread, send with thread_ids instead:

    cl.direct_send('hi there', thread_ids=[threads[0].id])

or use:

    cl.direct_answer(threads[0].id, 'hi there')

If this still fails on the current release with a real recipient user id or thread_ids, please open a new issue with the current instagrapi version, the exact helper used, and the response body from Instagram.
