### ISSUE TITLE
[BUG] Unable to login [macOS]

### ISSUE THREAD

**Issue by talhakabakus** [subzeroid/instagrapi#1626]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**
As the title is self-descriptive, I'm not able to login via my username & password.

**To Reproduce**
```
api = Client()
api.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
```

**Traceback**
  ```
File "/Users/talhakabakus/miniforge3/envs/autoDL/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "/Users/talhakabakus/miniforge3/envs/autoDL/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/talhakabakus/PycharmProjects/autoDL/run.py", line 26, in <module>
    main()
  File "/Users/talhakabakus/PycharmProjects/autoDL/run.py", line 17, in main
    api.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
  File "/Users/talhakabakus/miniforge3/envs/autoDL/lib/python3.11/site-packages/instagrapi/mixins/auth.py", line 441, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/talhakabakus/miniforge3/envs/autoDL/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 542, in private_request
    raise e
  File "/Users/talhakabakus/miniforge3/envs/autoDL/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 527, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Users/talhakabakus/miniforge3/envs/autoDL/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 416, in _send_private_request
    raise BadPassword(**last_json)
instagrapi.exceptions.BadPassword: The password you entered is incorrect. Please try again. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server

Process finished with exit code 1
```

**Expected behavior**
Authenticated client as a result of the successful login.

**Desktop (please complete the following information):**
```
 - OS: macOS Sonoma (14.0)
 - Python version: 3.11
 - instagrapi version: 2.0.0
```

**Comment by AlphaSoftwareInc** [comment]
I have the same error / bug.
One thing I noticed is that I also get this error message in instagram when I try to login in my Browser. I know for sure, that the password is correct since I changed it a few minutes ago and copied the password from a password manager.

**Comment by Akif-Efe** [comment]
I'm having the same problem for windows 10. What solution do you suggest? My information is correct but I cannot log in.

**Comment by Sinmania** [comment]
Same here, I am  running it on Ubuntu and it declines all my accounts. I would be more than happy if someone has a solution to share

**Comment by AvengerMoJo** [comment]
The login url https://i.instagram.com/api/v1/accounts/login/  no longer exist.

**Comment by cold9999** [comment]
I got this issue a week ago. but yesterday i got a advice(2fa login), and i tried to the method-it is working. Maybe instagram added more requests(or verification) in normal login. 2FA login is working now

**Comment by cold9999** [comment]
`
two_fa = input("2FA Code : ")
print("Login...")
client = instagrapi.Client()
client.login("ID","PW",verification_code=two_fa)
`

**Comment by AlphaSoftwareInc** [comment]
Does not work for me

**Comment by romanrsr** [comment]
+1

**Comment by Jasper-Rowan** [comment]
I am having this issue as well.

**Comment by spacehitchiker** [comment]
@talhakabakus I get that error often, it works for me when I login my instagram profile from the app/web and change my password from settings.

**Comment by Sinmania** [comment]
> @talhakabakus I get that error often, it works for me when I login my instagram profile from the app/web and change my password from settings.

How much time do you have between the errors?

**Comment by spacehitchiker** [comment]
> How much time do you have between the errors?

I usually login once and dump settings into a json file so it stays logged in. (See "Best Practices" in documentation), but I wasn't able to use this api much due to dm sending error, so I can't say much.

**Comment by nebula0225** [comment]
try session login

**Comment by AirFoxer** [comment]
Same here, see #1630
Also MacOS here, any workarounds yet?

**Comment by subzeroid** [comment]
Closing this as a duplicate of the canonical `BadPassword` login-trust thread: https://github.com/subzeroid/instagrapi/issues/1498

This is not a confirmed instagrapi code bug. One comment here reports the same password error in the Instagram browser login, which is a strong signal that Instagram is rejecting the account/IP/device trust state rather than an instagrapi response parser.

Compare the same credentials in the official Instagram app through the same proxy/IP/network identity used by the script. If the app also rejects them, resolve the account/network trust state first. If the app works under the same network identity, then inspect script-side device settings, saved session reuse, proxy assignment before `login()`, and login retry flow.

Troubleshooting guide: https://instagrapi.com/guides/errors/bad-password/

Docs backlink commit: https://github.com/subzeroid/instagrapi/commit/2ddeb63c95743b05d6ea3d6a1c67a7a6478d5936

For supported business workflows, use the official Instagram Platform API where it covers the use case: https://developers.facebook.com/docs/instagram-platform/

If you need hosted session/proxy/challenge handling instead of operating private API accounts yourself, see HikerAPI: https://hikerapi.com/p/fyfx6ygs
