### ISSUE TITLE
[BUG] ProxyAddressIsBlocked with all networks / vpns

### ISSUE THREAD

**Issue by AirFoxer** [subzeroid/instagrapi#1630]
No matter where I try to run my code (different networks, VPNs on/off) I always get this Error Message:

/usr/bin/python3 /Users/User/Documents/Python/data_collection.py 
/Library/Python/3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Library/Python/3.9/site-packages/instagrapi/mixins/private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "/Library/Python/3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/User/Documents/Python/data_collection.py", line 43, in <module>
    conversations = get_messages(username, password)
  File "/Users/User/Documents/Python/data_collection.py", line 11, in get_messages
    cl.login(username, password)
  File "/Library/Python/3.9/site-packages/instagrapi/mixins/auth.py", line 441, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "/Library/Python/3.9/site-packages/instagrapi/mixins/private.py", line 542, in private_request
    raise e
  File "/Library/Python/3.9/site-packages/instagrapi/mixins/private.py", line 527, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Library/Python/3.9/site-packages/instagrapi/mixins/private.py", line 447, in _send_private_request
    raise ProxyAddressIsBlocked(**last_json)
instagrapi.exceptions.ProxyAddressIsBlocked: Instagram has blocked your IP address, use a quality proxy provider (not free, not shared)

Process finished with exit code 1

**Comment by AvengerMoJo** [comment]
should be duplicated to #1625
Same error the request login url api has been removed. https://i.instagram.com/api/v1/accounts/login/

**Comment by subzeroid** [comment]
`ProxyAddressIsBlocked` means Instagram rejected the IP/proxy/network reputation for that request. There is no library-side fix for a blocked address; use a different trusted residential/mobile proxy or a cleaner network/session. Closing as environment/network-specific rather than an instagrapi bug.
