### ISSUE TITLE
[BUG]  Instagram has blocked your IP address, use a quality proxy provider (not free, not shared)

### ISSUE THREAD

**Issue by Lightkira3843** [subzeroid/instagrapi#1698]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**
when i try to login to instgram by instagrapi  by the following code 
```
from instagrapi import Client

user_id="insta mail"
password='insta passwd'

cl = Client()
cl.login(user_id, password)
cl.dump_settings("session.json")
```
the error i m getting 

**Traceback**
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/temp_instatest.py", line 7, in <module>
    cl.login(user_id, password)
  File "/home/kali/.local/lib/python3.11/site-packages/instagrapi/mixins/auth.py", line 441, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 542, in private_request
    raise e
  File "/home/kali/.local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 527, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/kali/.local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 447, in _send_private_request
    raise ProxyAddressIsBlocked(**last_json)
instagrapi.exceptions.ProxyAddressIsBlocked: Instagram has blocked your IP address, use a quality proxy provider (not free, not shared)

**Expected behavior**
it must dump the insta login session in session.json file 

**Screenshots**
![Screenshot_2023-12-14_21-22-47](https://github.com/subzeroid/instagrapi/assets/104569852/ac04ec3c-67ff-4121-ae05-5959ea7cf6d7)
![Screenshot_2023-12-14_21-23-34](https://github.com/subzeroid/instagrapi/assets/104569852/a7883bb4-34c5-4e03-9263-24df49aa4ce4)

**Desktop (please complete the following information):**
 - OS: Kali linux 2023.3
 - Python version 3.11.6
 - instagrapi version the current one
 - moveipy version if used
 - imagemagick version if used

**Additional context**
i have also tried the same thing on windows & on cloud server as well but keep getting the same error

**Comment by nebula0225** [comment]
use a quality proxy provider (not free, not shared)

**Comment by Diptonil** [comment]
Is this issue still not resolved?

**Comment by ranjitsingha** [comment]
Hi i am getting the same issue

**Comment by subzeroid** [comment]
`ProxyAddressIsBlocked` is an Instagram network/IP rejection, not a bug in `dump_settings()`.

The session file is not created because login never succeeds. Instagram rejected the current IP before the account could establish a valid private session.

Recommended handling:

- do not retry the same login repeatedly from the blocked IP
- switch to a cleaner, stable proxy/IP for that account
- keep country, locale, device settings, and saved session consistent
- once login succeeds, save settings and reuse them instead of logging in from scratch each run

Docs:

- Best Practices: https://subzeroid.github.io/instagrapi/usage-guide/best-practices.html
- `proxy_address_is_blocked` guide: https://instagrapi.com/guides/errors/proxy-address-is-blocked/
- Proxy setup guide: https://instagrapi.com/guides/instagrapi-proxy-setup/
