### ISSUE TITLE
[BUG] pydantic_core.ValidationError

### ISSUE THREAD

**Issue by Vladislav-Shi** [subzeroid/instagrapi#1705]
**Describe the bug**
I'm trying to get account information, but I'm getting a Pydantic error

The code I used:
```python
from instagrapi import Client

cl = Client(proxy='http:/my_proxy'')
cl.login('log', 'pass')
print(cl.account_info())

```

**Traceback**
```
Traceback (most recent call last):
  File "/home/vladislav/PycharmProjects/insta_parse/test.py", line 5, in <module>
    print(cl.account_info())
  File "/home/vladislav/PycharmProjects/insta_parse/.venv/lib/python3.10/site-packages/instagrapi/mixins/account.py", line 59, in account_info
    return extract_account(result["user"])
  File "/home/vladislav/PycharmProjects/insta_parse/.venv/lib/python3.10/site-packages/instagrapi/extractors.py", line 357, in extract_account
    return Account(**data)
  File "/home/vladislav/PycharmProjects/insta_parse/.venv/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Account
pk
  Input should be a valid string [type=string_type, input_value=63512676527, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
```

 - instagrapi version 2.0.1
 - pydantic version 2.5.2
 - pydantic-core 2.14.5

How can I fix this?

**Comment by lyubomyr-shaydariv** [comment]
I don't write Python code, but whatever is happening to the `instagrapi` and `pydantic` modules running together, downgrading to the `pydantic` major version 1 seems to work (1.10.13 is the latest as of today):

```shell
pip uninstall pydantic pydantic_core
pip install pydantic==1.10.13
```

Brainless @dependabot suggested b3ca76fad6bd6ec4ec100a15c0ff0c380a7f3688 that has been reverted in 70ff317d56764b52bb46ce8e85e1f10ac6422d42. Then the major version 2 was brought back in 82e257cdfe5ef842dcf41ce06eb9f1c3d9ab214c for whatever reason (was it accidentally committed along with `types.py`?). Just curious how it works for others if it eventually has been upgraded in f94765ebb7f343c93abc2641f376af3ce8c67490.

**Comment by SaitgalinKhannan** [comment]
I have this error too. I`m trying to get Story info.

pk = cl.story_pk_from_url(url)
story_info = cl.story_info(pk).model_dump_json()

_url is valid_

**Traceback:**
File "S:\KProjects\super_instagram\main.py", line 54, in story_handler
    story_info = cl.story_info(pk).model_dump_json()
                 ^^^^^^^^^^^^^^^^^
  File "S:\KProjects\super_instagram\venv\Lib\site-packages\instagrapi\mixins\story.py", line 92, in story_info
    story = self.story_info_v1(story_pk)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\KProjects\super_instagram\venv\Lib\site-packages\instagrapi\mixins\story.py", line 67, in story_info_v1
    stories = self.user_stories_gql(user_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\KProjects\super_instagram\venv\Lib\site-packages\instagrapi\mixins\story.py", line 174, in user_stories_gql
    user = self.users_stories_gql([user_id], amount=amount)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\KProjects\super_instagram\venv\Lib\site-packages\instagrapi\mixins\story.py", line 155, in users_stories_gql
    user.stories = [extract_story_gql(m) for m in items]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\KProjects\super_instagram\venv\Lib\site-packages\instagrapi\mixins\story.py", line 155, in <listcomp>
    user.stories = [extract_story_gql(m) for m in items]
                    ^^^^^^^^^^^^^^^^^^^^
  File "S:\KProjects\super_instagram\venv\Lib\site-packages\instagrapi\extractors.py", line 449, in extract_story_gql
    return Story(**story)
           ^^^^^^^^^^^^^^
  File "S:\KProjects\super_instagram\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Story
pk
  Input should be a valid string [type=string_type, input_value=3261427676799247488, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type

**Comment by Aaeeschylus** [comment]
> I don't write Python code, but whatever is happening to the `instagrapi` and `pydantic` modules running together, downgrading to the `pydantic` major version 1 seems to work (1.10.13 is the latest as of today):
> 
> ```shell
> pip uninstall pydantic pydantic_core
> pip install pydantic==1.10.13
> ```
> 
> Brainless @dependabot suggested [b3ca76f](https://github.com/subzeroid/instagrapi/commit/b3ca76fad6bd6ec4ec100a15c0ff0c380a7f3688) that has been reverted in [70ff317](https://github.com/subzeroid/instagrapi/commit/70ff317d56764b52bb46ce8e85e1f10ac6422d42). Then the major version 2 was brought back in [82e257c](https://github.com/subzeroid/instagrapi/commit/82e257cdfe5ef842dcf41ce06eb9f1c3d9ab214c) for whatever reason (was it accidentally committed along with `types.py`?). Just curious how it works for others if it eventually has been upgraded in [f94765e](https://github.com/subzeroid/instagrapi/commit/f94765ebb7f343c93abc2641f376af3ce8c67490).

This resolved this exact issue for me.

**Comment by lyubomyr-shaydariv** [comment]
> I don't write Python code, but whatever is happening to the `instagrapi` and `pydantic` modules running together, downgrading to the `pydantic` major version 1 seems to work (1.10.13 is the latest as of today):
> 
> ```shell
> pip uninstall pydantic pydantic_core
> pip install pydantic==1.10.13
> ```
> 
> Brainless @dependabot suggested [b3ca76f](https://github.com/subzeroid/instagrapi/commit/b3ca76fad6bd6ec4ec100a15c0ff0c380a7f3688) that has been reverted in [70ff317](https://github.com/subzeroid/instagrapi/commit/70ff317d56764b52bb46ce8e85e1f10ac6422d42). Then the major version 2 was brought back in [82e257c](https://github.com/subzeroid/instagrapi/commit/82e257cdfe5ef842dcf41ce06eb9f1c3d9ab214c) for whatever reason (was it accidentally committed along with `types.py`?). Just curious how it works for others if it eventually has been upgraded in [f94765e](https://github.com/subzeroid/instagrapi/commit/f94765ebb7f343c93abc2641f376af3ce8c67490).

The following configuration surprisingly works fine:

|module       |version|
|-------------|-------|
|instagrapi   |2.1.1  |
|pydantic     |2.6.4  |
|pydantic_core|2.17.0 |

No clue what changed in Instagrapi since then, but the quoted workaround should no longer be considered recommended, I guess.

**Comment by subzeroid** [comment]
The reported Pydantic v2 numeric ID validation failures are fixed in current releases by numeric-to-string coercion in the shared response models. Please upgrade to the latest instagrapi version and open a new issue with a current traceback if there is still a specific field that fails.
