### ISSUE TITLE
[BUG] TypeError when importing Client from instagrapi

### ISSUE THREAD

**Issue by Ricardomol** [subzeroid/instagrapi#1713]
**Describe the bug**
I get this error `TypeError: unsupported operand type(s) for |: 'type' and 'type'` just by simply importing `Client`, like this:
`from instagrapi import Client`.

I'm running the script on Mac OS, have created a Python virtual env and installed instagrapi, like this:
```
python -m venv venv
source venv/bin/activate
pip install instagrapi
python test.py
```

**To Reproduce**
```python
from instagrapi import Client
````

**Traceback**
```python
Traceback (most recent call last):
  File "/Users/me/work/engager/instagrapi/test2.py", line 1, in <module>
    from instagrapi import Client
  File "/Users/me/work/engager/instagrapi/venv/lib/python3.9/site-packages/instagrapi/__init__.py", line 7, in <module>
    from instagrapi.mixins.account import AccountMixin
  File "/Users/me/work/engager/instagrapi/venv/lib/python3.9/site-packages/instagrapi/mixins/account.py", line 8, in <module>
    from instagrapi.extractors import extract_account, extract_user_short
  File "/Users/me/work/engager/instagrapi/venv/lib/python3.9/site-packages/instagrapi/extractors.py", line 6, in <module>
    from .types import (
  File "/Users/me/work/engager/instagrapi/venv/lib/python3.9/site-packages/instagrapi/types.py", line 130, in <module>
    class Media(BaseModel):
  File "/Users/me/work/engager/instagrapi/venv/lib/python3.9/site-packages/instagrapi/types.py", line 131, in Media
    pk: str | int
TypeError: unsupported operand type(s) for |: 'type' and 'type'
````

**Expected behavior**
The `Client`object should be imported correctly.

**Desktop (please complete the following information):**
 - OS: macOs Ventura 13.5 
 - Python version 3.9.10
 - instagrapi version 2.0.1

**Comment by Ricardomol** [comment]
I managed to move on by switching from Python 3.9 to 3.10. However, the docs say this is compatible with Python >= 3.9.

**Comment by praveencqr** [comment]
I installed it on Python 3.10 and it works fine now. Python 3.9 doesn't support the latest version.

**Comment by subzeroid** [comment]
For current instagrapi versions, this is a Python-version issue rather than a current library bug.

Current instagrapi requires Python 3.10+. The error `TypeError: unsupported operand type(s) for |: type and type` happens when code using `str | int` annotations is imported on Python 3.9.

Please upgrade the runtime to Python 3.10+ and reinstall instagrapi. Python 3.11 or 3.12 is recommended. If you must stay on Python 3.9, pin an older package version such as `instagrapi==2.4.5` instead of installing the latest release.
