### ISSUE TITLE
[BUG] TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by Nickhenry784** [subzeroid/instagrapi#1719]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**

**To Reproduce**
Provide a piece of code to reproduce the problem.

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04]
 - Python version [e.g. 3.8.3]
 - instagrapi version [e.g. 1.9.3, not "latest"]
 - moveipy version if used
 - imagemagick version if used

**Additional context**
Hello, I was testing your package and got this error.
from instagrapi import Client

cl = Client()
USERNAME = "abc"
PASSWORD = "sdeerre"

cl.login(USERNAME, PASSWORD)

Error: Traceback (most recent call last):
  File "f:\Python\ins.py", line 1, in <module>
    from instagrapi import Client
  File "~\Python\Python39\lib\site-packages\instagrapi\__init__.py", line 7, in <module>
    from instagrapi.mixins.account import AccountMixin
  File "~\Python\Python39\lib\site-packages\instagrapi\mixins\account.py", line 8, in <module>
    from instagrapi.extractors import extract_account, extract_user_short
  File "~\Python\Python39\lib\site-packages\instagrapi\extractors.py", line 6, in <module>
    from .types import (
  File "~\Python\Python39\lib\site-packages\instagrapi\types.py", line 130, in <module>
    class Media(BaseModel):
  File "~\Python\Python39\lib\site-packages\instagrapi\types.py", line 131, in Media
    pk: str | int
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by enakhi** [comment]
instad-web-1  | Traceback (most recent call last):
instad-web-1  |   File "/app/app.py", line 10, in <module>
instad-web-1  |     from UserInfo import UserInfo
instad-web-1  |   File "/app/UserInfo.py", line 5, in <module>
instad-web-1  |     from instagrapi import Client
instad-web-1  |   File "/usr/local/lib/python3.9/site-packages/instagrapi/__init__.py", line 7, in <module>
instad-web-1  |     from instagrapi.mixins.account import AccountMixin
instad-web-1  |   File "/usr/local/lib/python3.9/site-packages/instagrapi/mixins/account.py", line 8, in <module>
instad-web-1  |     from instagrapi.extractors import extract_account, extract_user_short
instad-web-1  |   File "/usr/local/lib/python3.9/site-packages/instagrapi/extractors.py", line 6, in <module>
instad-web-1  |     from .types import (
instad-web-1  |   File "/usr/local/lib/python3.9/site-packages/instagrapi/types.py", line 130, in <module>
instad-web-1  |     class Media(BaseModel):
instad-web-1  |   File "/usr/local/lib/python3.9/site-packages/instagrapi/types.py", line 131, in Media
instad-web-1  |     pk: str | int
instad-web-1  | TypeError: unsupported operand type(s) for |: 'type' and 'type'
I have the same issue

**Comment by tbass134** [comment]
I had the same issue. switching to python 3.11 works for me

**Comment by Altimis** [comment]
Switch to python 3.10

**Comment by Moddingus** [comment]
Hey guys, the issue comes from types.py in /Python/3.9/lib/python/site-packages/instagrapi/types.py. In line 125 the old union operator is used. change line 2 to `from typing import List, Optional, Union` and change line 25 to `pk: Union[str, int]`. repeat the same process anytime `|` is used. hope that makes sense lol.

**Comment by subzeroid** [comment]
This has the same root cause as the other Python 3.9 import reports.

Current instagrapi releases require Python 3.10+. Python 3.9 cannot import annotations such as `str | int`, which produces this `TypeError` during import.

Use Python 3.10+ and reinstall instagrapi. If the project is locked to Python 3.9, pin an older supported package version such as `instagrapi==2.4.5` instead of using the latest release.
