### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JayTongue** [subzeroid/instagrapi#1755]
My current code is:

```
album = ['temp/temp_0_0.jpg', 'temp/temp_0_1.jpg', 'temp/temp_0_2.jpg']
for story in album:
        story = Path(story)
        bot.photo_upload_to_story(path=story, caption='')
```

And I get:

```
Traceback (most recent call last):
  File "D:\Python Projects\Post Scheduler\with_instagrapi.py", line 111, in <module>
    main()
  File "D:\Python Projects\Post Scheduler\with_instagrapi.py", line 17, in main
    run_bot(post)
  File "D:\Python Projects\Post Scheduler\with_instagrapi.py", line 73, in run_bot
    bot.photo_upload_to_story(path=story, caption='')
  File "C:\Users\_____\AppData\Local\miniconda3\Lib\site-packages\instagrapi\mixins\photo.py", line 394, in photo_upload_to_story
    return Story(
           ^^^^^^
  File "C:\Users\jct3368\AppData\Local\miniconda3\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Story
pk
  Input should be a valid string [type=string_type, input_value=3284033950949101872, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
```

I've tried to get both using Path() and str(), but neither works to satisfy the input datatype error.

**Comment by subzeroid** [comment]
This old Story `pk` validation error is fixed in current releases by numeric-to-string coercion in the shared response models. Please upgrade to the latest instagrapi version and reopen with a fresh traceback if `photo_upload_to_story` still fails.
