### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TsunamiWind** [subzeroid/instagrapi#1770]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**
When attempting to log-in a error code 400 is given.

**To Reproduce**
```
cl = Client()
cl.login("", "")   
```

**Traceback**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

Traceback (most recent call last):
  File "/home/bot.py", line 13, in <module>
    cl.login("", "")       
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/instagrapi/mixins/auth.py", line 441, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/instagrapi/mixins/private.py", line 541, in private_request
    raise e
  File "/usr/local/lib/python3.11/dist-packages/instagrapi/mixins/private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/instagrapi/mixins/private.py", line 448, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: We couldn't find an account with the username ########. Check the username you entered and try again.
```

**Expected behavior**
The login process to successfully occur

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Python version 3.8.3
 - instagrapi version (latest)

**Comment by enakhi** [comment]
UnknownError
We couldn't find an account with the username rezavishkaa. Check the username you entered and try again.

Recently, I am getting this error.

**Comment by eloufirjawad** [comment]
same here

**Comment by 425107265** [comment]
> UnknownError We couldn't find an account with the username rezavishkaa. Check the username you entered and try again.
> 
> Recently, I am getting this error.

I also encountered this problem.Any idea how to solve it?

**Comment by automagic2** [comment]
It's not just this api that has this same error. I tested another api in Typescript and the exact same error occurs.
I noticed that in my case it only happens on newer profiles, but this error does not occur when logging in via the browser.
Old profiles apparently do not have this error.

**Comment by 425107265** [comment]
知学网重装上阵 -  http://www.zhixue365.com  立足郑州面向六大群体的本地化培训信息交流展示平台，会员征集中，送给所有有需求的亲们！

**Comment by 425107265** [comment]
> It's not just this api that has this same error. I tested another api in Typescript and the exact same error occurs. I noticed that in my case it only happens on newer profiles, but this error does not occur when logging in via the browser. Old profiles apparently do not have this error.

I am using the Instagram library. When calling the login method, it will prompt We couldn't find an account with the username xxxxxxx. Check the username you entered and try again. This is especially serious today.

**Comment by uccio99** [comment]
I have same problem

**Comment by radityafs** [comment]
any solution please, have same issue here

**Comment by inrl-official** [comment]
> any solution please, have same issue here

Same🤔

**Comment by BitDownMod** [comment]
The same for me: "We couldn't find an account with the username. Check the username you entered and try again."

**Comment by enakhi** [comment]
I checked the instagram app,this error shows even on the Instagram app
![image](https://github.com/subzeroid/instagrapi/assets/8220546/2a42ff68-e26e-4034-b991-f4862ea418fd)
that's interesting if I give wrong username the error will change
![image](https://github.com/subzeroid/instagrapi/assets/8220546/8acf9a48-dd43-4452-a6f2-f6fc349ad8eb)

**Comment by marschr** [comment]
I've seen this error in the past when trying to log in to my account in the app, just like the screenshots above, with nothing related to the libraries. Seems like sometimes the database sharding on the ig server side doesn't properly update. Doesn't seem to be on our end =( I'd wait for a few hours.
Is this for fresh logins only? Has anyone tried with existing cookies/session?

**Comment by BitDownMod** [comment]
it's more than 24 hours already

**Comment by BitDownMod** [comment]
I have 11 year old account and it working fine with instagrapi. I tested just a few seconds ago, but not with 3 yo account.

**Comment by BitDownMod** [comment]
Old account is fine with fresh login and with existing session. New account doesn't work.

**Comment by tinerci** [comment]
> UnknownError We couldn't find an account with the username rezavishkaa. Check the username you entered and try again.
> 
> Recently, I am getting this error.



> I've seen this error in the past when trying to log in to my account in the app, just like the screenshots above, with nothing related to the libraries. Seems like sometimes the database sharding on the ig server side doesn't properly update. Doesn't seem to be on our end =( I'd wait for a few hours. Is this for fresh logins only? Has anyone tried with existing cookies/session?



> Old account is fine with fresh login and with existing session. New account doesn't work.



> UnknownError We couldn't find an account with the username rezavishkaa. Check the username you entered and try again.
> 
> Recently, I am getting this error.


Friends, Instagram no longer uses old versions of accounts/login. There is a new login method. Now I am logging in with the new method. Instagram is no longer functional. Those who want to buy my method should contact @phpkertenkele on telegram.

**Comment by enakhi** [comment]
@adw0rd do you have any idea to solve this problem?

**Comment by mirubinstein** [comment]
Seeing this as well - suddenly regressed yesterday. No account or code change.

**Comment by hailovigor** [comment]
Same problem

**Comment by PyaScrapz** [comment]
🚨

**Comment by Reloisback** [comment]
Nobody knows if they're working on it or not, they don't say anything

**Comment by tinerci** [comment]
> Nobody knows if they're working on it or not, they don't say anything

I have a new login method, it works without any problems, we can test it. Those who want to buy can reach @phpkertenkele on telegram.

**Comment by tinerci** [comment]
> 🚨

I have a new login method, it works without any problems, we can test it. Those who want to buy can reach @phpkertenkele on telegram.

**Comment by Reloisback** [comment]
Much better to wait for admins to update :)

**Comment by tinerci** [comment]
> Much better to wait for admins to update :)

administrators will not be able to solve this. :)

**Comment by Reloisback** [comment]
Can't the person who wrote this library solve this? 
Funny

**Comment by AlloryDante** [comment]
Same error...

**Comment by alenko** [comment]
> > Much better to wait for admins to update :)
> 
> administrators will not be able to solve this. :)

lol, common. Stop spreading false news. And yes they will. I will send them solution

**Comment by Reloisback** [comment]
> > > Much better to wait for admins to update :)
> > 
> > 
> > administrators will not be able to solve this. :)
> 
> lol, common. Stop spreading false news. And yes they will. I will send them solution

Thank you, is it possible to share this in the Telegram group or here? Since we can't contact anyone, we can at least use it until it's updated.

**Comment by uccio99** [comment]
any news?

**Comment by PyaScrapz** [comment]
> > Much better to wait for admins to update :)
> 
> administrators will not be able to solve this. :)

why?

**Comment by gauravsingh06** [comment]
![telegram-cloud-photo-size-5-6167809028785289738-y](https://github.com/subzeroid/instagrapi/assets/73547597/19f11fce-29c8-4bcc-8af7-89f9c40e4979)

**Hey Everyone GoodNews!**

I got the fix, I have tried this 5 accounts. It worked. 

You have noticed that when you try to login the same account on instagram app you face the error right?

So I thought it’s an issue from instagram ends. Yesterday someone told in github. 

I was randomly trying different method but nothing worked, I tried changing headers but didn’t work. 

**_I tried bruteforcing the login function. My account got logged in after exact 20 request on each of the 5 accounts. I think instagram servers are not getting updated properly but when request 20 times it updates it_** 

Please someone try and let me know. I was constantly working from 24 hours to figure the bug.

**Comment by marschr** [comment]
> I tried bruteforcing the login function. My account got logged in after exact 20 request on each of the 5 accounts. I think instagram servers are not getting updated properly but when request 20 times it updates it

That somewhat makes sense, back in the day when I tried to login to reactivate a deactivated account I've only got it working after trying a lot of times. Now, how does that relates to the library and the login flow I wish I'd know.

**Comment by ofarukbicer** [comment]
Hi guys,

I'm having the same problems

I think Instagram released a new API,

/api/v1/accounts/login/ OFF only login with phone number and email address works

new API endpoint /api/v1/bloks/apps/com.bloks.www.bloks.caa.login.async.send_login_request/

I will work on this, if I find it, I will leave a note here. If anyone finds it before me, can you please let me know, thank you.

**Comment by gauravsingh06** [comment]
Till now, I have don't know how it's gonna get fixed without bruteforce. But I think you can bypass the cache with headers, but I don't know which header value need to be altered. I tried cache-control but it doesn't work. Devs of this libs know much better about headers, they might fix it.

**Comment by ofarukbicer** [comment]
My friend, most everyone is having the same problem as the friend who opened the issue, and this happened today. Instagram released a very nice update because I had a working system before, we will probably spend our days solving the new API. I hope the developers you mentioned can help.

**Comment by enakhi** [comment]
> ![telegram-cloud-photo-size-5-6167809028785289738-y](https://private-user-images.githubusercontent.com/73547597/299797488-19f11fce-29c8-4bcc-8af7-89f9c40e4979.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMTk4MzgsIm5iZiI6MTcwNjIxOTUzOCwicGF0aCI6Ii83MzU0NzU5Ny8yOTk3OTc0ODgtMTlmMTFmY2UtMjljOC00YmNjLThhZjctODlmOWM0MGU0OTc5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDIxNTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZDU5OGFiZDMzMjg4YzJiYTUyN2FjNWJhYTA0NzJjZWIxNzg0YTVmZTQ0NmEwZWQ5MzA1ODU2YjlhMmZkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eTiguXmV7iHtgjeMcTbSZ6QCNvQjy9-DcYtPUz1R8fs)
> 
> **Hey Everyone GoodNews!**
> 
> I got the fix, I have tried this 5 accounts. It worked.
> 
> You have noticed that when you try to login the same account on instagram app you face the error right?
> 
> So I thought it’s an issue from instagram ends. Yesterday someone told in github.
> 
> I was randomly trying different method but nothing worked, I tried changing headers but didn’t work.
> 
> **_I tried bruteforcing the login function. My account got logged in after exact 20 request on each of the 5 accounts. I think instagram servers are not getting updated properly but when request 20 times it updates it_**
> 
> Please someone try and let me know. I was constantly working from 24 hours to figure the bug.

Thanks, this worked for me. After exactly 20 requests, it worked. We could use this method until a better solution arrives.

**Comment by uccio99** [comment]
It seems that the problem has re-entered automatically. Can anyone confirm?

**Comment by marschr** [comment]
Here's now working just fine. Very odd behavior from the ig server side.

**Comment by Cedrick-J** [comment]
Doing an Instagram password reset fixed this for me

**Comment by darkzbaron** [comment]
Same here

**Comment by subzeroid** [comment]
Closing as not planned. The thread already confirms the same `We could not find an account...` error appeared in the official Instagram app and later resolved/changed server-side. That points to Instagram account/cache/login state rather than a library bug. Please use an existing valid session or complete/reset the account state in the official app before using instagrapi.
