### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'[BUG]

### ISSUE THREAD

**Issue by usmanyaqoob49** [subzeroid/instagrapi#1803]
for simple this code:
cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)

user_id = cl.user_id_from_username(ACCOUNT_USERNAME)
medias = cl.user_medias(user_id, 20)

Traceback (most recent call last):
  File "E:\JMM\JMMProjects\SMLT\scrapers\insta.py", line 1, in <module>
    from instagrapi import Client
  File "E:\JMM\JMMProjects\SMLT\myenv\lib\site-packages\instagrapi\__init__.py", line 7, in <module>
    from instagrapi.mixins.account import AccountMixin
  File "E:\JMM\JMMProjects\SMLT\myenv\lib\site-packages\instagrapi\mixins\account.py", line 8, in <module>
    from instagrapi.extractors import extract_account, extract_user_short
  File "E:\JMM\JMMProjects\SMLT\myenv\lib\site-packages\instagrapi\extractors.py", line 7, in <module>
    from .types import (
  File "E:\JMM\JMMProjects\SMLT\myenv\lib\site-packages\instagrapi\types.py", line 124, in <module>
    class Media(TypesBaseModel):
  File "E:\JMM\JMMProjects\SMLT\myenv\lib\site-packages\instagrapi\types.py", line 125, in Media
    pk: str | int
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by tajbowness** [comment]
Share more code before cl.login, as in the exception its not noted at all with the code you shared.

> File "E:\JMM\JMMProjects\SMLT\scrapers\insta.py", line 1, in
> from instagrapi import Client
> File "E:\JMM\JMMProjects\SMLT\myenv\lib\site-packages\instagrapi__init__.py", line 7, in
> from instagrapi.mixins.account import AccountMixin

**Comment by huskydj1** [comment]
Try using python 3.10. I received this error on python 3.9, but it was fine in a clean conda environment with 3.10.

**Comment by ycaty** [comment]
Found error on python3.8 seems to be cause from this line `pk: str | int`

Here's a quick fix
in types.py file we add import Union
#change this
`from typing import List, Optional   `
#to this
`from typing import List, Optional,  Union  `


Next Under the Media class 

#change this
` 
class Media(BaseModel):
    pk: str | int`

#to this
`class Media(BaseModel):
    pk: Union[str, int]`

**Comment by subzeroid** [comment]
This is the same Python-version issue covered by the other `str | int` import reports.

Current instagrapi requires Python 3.10+. Python 3.9 and older cannot import annotations such as `str | int`, so the import fails before your script reaches `cl.login(...)`.

Fix:

- use Python 3.10+ and reinstall instagrapi, preferably Python 3.11 or 3.12
- if the project is locked to Python 3.9, pin an older package version such as `instagrapi==2.4.5`
- do not patch files inside `site-packages`; the next install will overwrite those changes

Related closed reports: #1713 and #1719.
