### ISSUE TITLE
Collections 

### ISSUE THREAD

**Issue by monafHorany** [subzeroid/instagrapi#1808]
in Collections 
media_save(media_id: str, collection_pk: int = None)

from instagrapi import Client

cl = Client()
cl.login('username', 'password')
cl.media_save('3303854334267244331_65063116664',
              collection_pk=18085719163386811_65063116664)

the error is: 

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\istagram_api\Lib\site-packages\instagrapi\mixins\private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "C:\ProgramData\anaconda3\envs\istagram_api\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/3303854334267244331/save/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\oxo\Documents\instagram_backend\instagram-backend\python_functions\login.py", line 8, in <module>
    cl.media_save('3303854334267244331_65063116664')
  File "C:\ProgramData\anaconda3\envs\istagram_api\Lib\site-packages\instagrapi\mixins\collection.py", line 221, in media_save
    result = self.private_request(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\istagram_api\Lib\site-packages\instagrapi\mixins\private.py", line 541, in private_request
    raise e
  File "C:\ProgramData\anaconda3\envs\istagram_api\Lib\site-packages\instagrapi\mixins\private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\ProgramData\anaconda3\envs\istagram_api\Lib\site-packages\instagrapi\mixins\private.py", line 448, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: You cannot save this media.

**Comment by subzeroid** [comment]
Closing as not planned. `You cannot save this media` is the server response from Instagram for that media/account/collection combination, usually visibility/eligibility/permission state, not a client-side parsing issue. If the same media can be saved in the official app with the same account and current instagrapi cannot save it, please open a fresh issue with the current request details. Docs: https://subzeroid.github.io/instagrapi/usage-guide/collection.html
