### ISSUE TITLE
400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/two_factor_login/

### ISSUE THREAD

**Issue by rui4ymipat** [subzeroid/instagrapi#1854]
My code show error
 Traceback (most recent call last):
  File "C:\Users\iHC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instagrapi\mixins\private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "C:\Users\iHC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 1021, in raise_for_status    
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/two_factor_login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\iHC\Desktop\pisfacebook\social-scraper-v2\test.py", line 71, in <module>
    login()
  File "C:\Users\iHC\Desktop\pisfacebook\social-scraper-v2\test.py", line 57, in login
    cl.login(IG_USERNAME, IG_PASSWORD,
  File "C:\Users\iHC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instagrapi\mixins\auth.py", line 465, in login
    logged = self.private_request(
  File "C:\Users\iHC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instagrapi\mixins\private.py", line 542, in private_request
    raise e
  File "C:\Users\iHC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instagrapi\mixins\private.py", line 527, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\iHC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instagrapi\mixins\private.py", line 449, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Invalid Parameters

my code  for login
`
 cl.login(IG_USERNAME, IG_PASSWORD,
                 verification_code=cl.totp_generate_code(otp_seed))
`

I try to print username , password and otp then go login in ig website , it can login . but my code show error like this

**Comment by web61rus** [comment]
I have the same problem

**Comment by sb0y** [comment]
Same issue here

```python
warp_beacon  | 2024-08-11 18:47:25,571 - root - ERROR - Invalid Parameters
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
warp_beacon  |     response.raise_for_status()
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
warp_beacon  |     raise HTTPError(http_error_msg, response=self)
warp_beacon  | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/auth.py", line 441, in login
warp_beacon  |     logged = self.private_request("accounts/login/", data, login=True)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 541, in private_request
warp_beacon  |     raise e
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 526, in private_request
warp_beacon  |     self._send_private_request(endpoint, **kwargs)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 419, in _send_private_request
warp_beacon  |     raise TwoFactorRequired(**last_json)
warp_beacon  | instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/instagram.py", line 64, in login
warp_beacon  |     self.cl.login(username=username, password=password, verification_code=verification_code)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/auth.py", line 447, in login
warp_beacon  |     raise TwoFactorRequired(
warp_beacon  | instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required (you did not provide verification_code for login method)
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
warp_beacon  |     response.raise_for_status()
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
warp_beacon  |     raise HTTPError(http_error_msg, response=self)
warp_beacon  | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/auth.py", line 441, in login
warp_beacon  |     logged = self.private_request("accounts/login/", data, login=True)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 541, in private_request
warp_beacon  |     raise e
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 526, in private_request
warp_beacon  |     self._send_private_request(endpoint, **kwargs)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 419, in _send_private_request
warp_beacon  |     raise TwoFactorRequired(**last_json)
warp_beacon  | instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
warp_beacon  |     response.raise_for_status()
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
warp_beacon  |     raise HTTPError(http_error_msg, response=self)
warp_beacon  | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/two_factor_login/
warp_beacon  |
warp_beacon  | During handling of the above exception, another exception occurred:
warp_beacon  |
warp_beacon  | Traceback (most recent call last):
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/instagram.py", line 206, in download
warp_beacon  |     scrap_type, media_id = self.scrap(url)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/instagram.py", line 74, in scrap
warp_beacon  |     self.load_session()
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/instagram.py", line 52, in load_session
warp_beacon  |     self.login()
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/instagram.py", line 71, in login
warp_beacon  |     return self.login()
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/warp_beacon/scraper/instagram.py", line 64, in login
warp_beacon  |     self.cl.login(username=username, password=password, verification_code=verification_code)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/auth.py", line 465, in login
warp_beacon  |     logged = self.private_request(
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 541, in private_request
warp_beacon  |     raise e
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 526, in private_request
warp_beacon  |     self._send_private_request(endpoint, **kwargs)
warp_beacon  |   File "/usr/local/lib/python3.10/dist-packages/instagrapi/mixins/private.py", line 448, in _send_private_request
warp_beacon  |     raise UnknownError(**last_json)
warp_beacon  | instagrapi.exceptions.UnknownError: Invalid Parameters
```

**Comment by imnyang** [comment]
I have same problem
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/auth.py", line 441, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 541, in private_request
    raise e
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 419, in _send_private_request
    raise TwoFactorRequired(**last_json)
instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/app/library/init-auth.py", line 22, in <module>
    cl.login(INSTAGRAM_AUTH[0], INSTAGRAM_AUTH[1], cl.totp_generate_code(INSTAGRAM_AUTH[2]))
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/auth.py", line 447, in login
    raise TwoFactorRequired(
instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required (you did not provide verification_code for login method)
root@504b32aa7233:/code/app# nano library/init-auth.py 
root@504b32aa7233:/code/app# python3 library/init-auth.py 
521160
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/auth.py", line 441, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 541, in private_request
    raise e
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 419, in _send_private_request
    raise TwoFactorRequired(**last_json)
instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/app/library/init-auth.py", line 23, in <module>
    cl.login(INSTAGRAM_AUTH[0], INSTAGRAM_AUTH[1], cl.totp_generate_code(INSTAGRAM_AUTH[2]))
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/auth.py", line 447, in login
    raise TwoFactorRequired(
instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required (you did not provide verification_code for login method)
```

is it solved?

**Comment by subzeroid** [comment]
Closing as a duplicate of #1906. This is the same legacy two-factor invalid_parameters path. Please upgrade to instagrapi 2.7.11 or newer and use the current login/2FA flow; open a fresh issue only if the latest release still fails with sanitized last_json and traceback.
