### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ATOM27** [subzeroid/instagrapi#1866]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**
I have an 400 Bad request error when try to login and then instagrapi calls https://i.instagram.com/api/v1/feed/reels_tray/ and I get 

  ```
File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eugene_mekhedov/TelegramBot/hello.py", line 141, in <module>
    start()
  File "/home/eugene_mekhedov/TelegramBot/hello.py", line 135, in start
    instagram.login()
  File "/home/eugene_mekhedov/TelegramBot/InstagramEditor.py", line 14, in login
    instClient.login("market_news_by_yevhen", "muwpi0-fukjot-mimjIvm", relogin=True)
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/auth.py", line 472, in login
    self.login_flow()
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/auth.py", line 186, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/auth.py", line 277, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 541, in private_request
    raise e
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 448, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: consent_required
```

**To Reproduce**
Provide a piece of code to reproduce the problem.
just call login method.

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.

 ```
File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eugene_mekhedov/TelegramBot/hello.py", line 141, in <module>
    start()
  File "/home/eugene_mekhedov/TelegramBot/hello.py", line 135, in start
    instagram.login()
  File "/home/eugene_mekhedov/TelegramBot/InstagramEditor.py", line 14, in login
    instClient.login("market_news_by_yevhen", "muwpi0-fukjot-mimjIvm", relogin=True)
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/auth.py", line 472, in login
    self.login_flow()
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/auth.py", line 186, in login_flow
    check_flow.append(self.get_reels_tray_feed("cold_start"))
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/auth.py", line 277, in get_reels_tray_feed
    return self.private_request("feed/reels_tray/", data)
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 541, in private_request
    raise e
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/home/eugene_mekhedov/.local/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 448, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: consent_required
```

**Expected behavior**
I expect to login without error

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python version 3.9
 - instagrapi version 2.1.1
 - moveipy 6.0.2

**Additional context**
Interesting thing that if I ran my code on my mac it works fine, but when I try to launch

**Comment by tajbowness** [comment]
I think you've included your password in the traceback.

Last line `instagrapi.exceptions.UnknownError: consent_required `
Hints that you may have 2FA?

**Comment by ATOM27** [comment]
@tajbowness Thank you)
No, I don't have 2FA

**Comment by paboum** [comment]
Had the same error. Simply used the standard client to open profile page, got the data collection consent form to click through and it got back to work. But perhaps the API should include a method to do just that?

**Comment by fishfree** [comment]
@paboum I have the same problem. How do you make it? Would you pls share the detailed operation steps?

**Comment by subzeroid** [comment]
Closing as not planned. This was instagrapi 2.1.1 and the server returned `consent_required` on Google Cloud after login; that is account/region/IP consent/risk state from Instagram, not a code path we can fix generically. Upgrade to the latest release, complete any consent/checkpoint in the official app/browser, then reuse a saved session. Also rotate the password if it was pasted publicly.
