### ISSUE TITLE
[BUG] raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

### ISSUE THREAD

**Issue by StreakProgrammer** [subzeroid/instagrapi#1873]
I have an 400 Bad request error when try to login and then instagrapi calls https://i.instagram.com/api/v1/accounts/login/ and I get

Traceback (most recent call last):
  File "C:\Users\DNL-Dami\Documents\CODES\Instragram Bot\env\Lib\site-packages\instagrapi\mixins\private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "C:\Users\DNL-Dami\Documents\CODES\Instragram Bot\env\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\DNL-Dami\Documents\CODES\Instragram Bot\bot.py", line 7, in <module>
    client.login(username, password)
  File "C:\Users\DNL-Dami\Documents\CODES\Instragram Bot\env\Lib\site-packages\instagrapi\mixins\auth.py", line 
441, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DNL-Dami\Documents\CODES\Instragram Bot\env\Lib\site-packages\instagrapi\mixins\private.py", line 541, in private_request
    raise e
  File "C:\Users\DNL-Dami\Documents\CODES\Instragram Bot\env\Lib\site-packages\instagrapi\mixins\private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\DNL-Dami\Documents\CODES\Instragram Bot\env\Lib\site-packages\instagrapi\mixins\private.py", line 382, in _send_private_request
    raise PleaseWaitFewMinutes(e, response=e.response, **last_json)
instagrapi.exceptions.PleaseWaitFewMinutes: Please wait a few minutes before you try again.
```**_**

**Comment by tajbowness** [comment]
Instagram has banned your session. Create a new session id and relog

https://subzeroid.github.io/instagrapi/usage-guide/interactions.html

https://github.com/subzeroid/instagrapi/blob/master/docs/usage-guide/best-practices.md

**Comment by subzeroid** [comment]
Closing as not planned. PleaseWaitFewMinutes is an Instagram risk/rate-limit response for the account/session/IP, not a malformed instagrapi request. Stop retrying, wait, use a stable saved session, and follow the best-practices guidance before opening a fresh issue with a current sanitized traceback.
