### ISSUE TITLE
Public method for user_info_by_username_gql throws a simplejson.errors.JSONDecodeError[BUG]

### ISSUE THREAD

**Issue by golden23** [subzeroid/instagrapi#1889]
**Describe the bug**
I'm trying to get user information by public method [user_info_by_username_gql(username)], but I'm getting a "simplejson.errors.JSONDecodeError" error

**To Reproduce**
```
cl = Client()
cl.delay_range = [1, 5]
user_name = "cristiano"
user_info = cl.user_info_by_username_gql(user_name)
print(user_info)
```

**Traceback**
```
Traceback (most recent call last):
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 172, in _send_public_request
    self.last_public_json = response.json()
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gongdx/py_project/network_monitor/scripts/test2/Instagram_spider/instagraapi_demo.py", line 325, in <module>
    scraper_user_demo_anonymous(target_user)
  File "/Users/gongdx/py_project/network_monitor/scripts/test2/Instagram_spider/instagraapi_demo.py", line 304, in scraper_user_demo_anonymous
    user_info = cl.user_info_by_username_gql(user_name)
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/instagrapi/mixins/user.py", line 144, in user_info_by_username_gql
    return extract_user_gql(self.public_a1_request(f"/{username!s}/")["user"])
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 216, in public_a1_request
    response = self.public_request(
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 122, in public_request
    raise e
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 99, in public_request
    return self._send_public_request(url, **kwargs)
  File "/Users/gongdx/py_project/network_monitor/venv/lib/python3.9/site-packages/instagrapi/mixins/public.py", line 186, in _send_public_request
    raise ClientJSONDecodeError(
instagrapi.exceptions.ClientJSONDecodeError: JSONDecodeError Expecting value: line 1 column 1 (char 0) while opening https://www.instagram.com/cristiano/
```

**Comment by golden23** [comment]
the same error with other public methods like : user_following_gql,user_followers_gql,user_info_gql...

**Comment by SaeidB** [comment]
fix https://github.com/subzeroid/instagrapi/pull/1868/

**Comment by subzeroid** [comment]
Closing as addressed by current public username lookup behavior. This report came from the old public A1 profile path; current releases use the newer web profile lookup path. Please upgrade to instagrapi 2.7.11 or newer, and open a fresh issue if the same JSONDecodeError still reproduces there.
