### ISSUE TITLE
Pin comment [BUG]

### ISSUE THREAD

**Issue by SoFo12** [subzeroid/instagrapi#1899]
**Describe the bug**
When tried to pin the comment have the error. Comment is exist.

**To Reproduce**
`        comment =  self.account_manager.cl.media_comment(media.id, comment)
        self.account_manager.cl.comment_pin(media.id, comment.pk) if pin else None`

**Traceback**
Traceback (most recent call last):
  File "/Users/personal/DEV/video/account_manage/instagram_post_manager.py", line 45, in post
    self.leave_comment(media, "Test Message")
  File "/Users/personal/DEV/video/account_manage/instagram_post_manager.py", line 64, in leave_comment
    self.account_manager.cl.comment_pin(media.id, comment.pk) if pin else None
  File "/Users/personal/mambaforge/envs/video/lib/python3.9/site-packages/instagrapi/mixins/comment.py", line 249, in comment_pin
    result = self.private_request(
  File "/Users/personal/mambaforge/envs/video/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 542, in private_request
    raise e
  File "/Users/personal/mambaforge/envs/video/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 527, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Users/personal/mambaforge/envs/video/lib/python3.9/site-packages/instagrapi/mixins/private.py", line 466, in _send_private_request
    raise ClientError(e, response=e.response, **last_json)
instagrapi.exceptions.ClientError: 405 Client Error: Method Not Allowed for url: https://i.instagram.com/api/v1/media/someid/pin_comment/somepk/

**Expected behavior**
Comment pinned

**Desktop (please complete the following information):**
 - OS: [MAC OS 13.0.1]
 - Python version [3.9.19]
 - instagrapi version [2.1.1]

**Comment by luckyAkbar** [comment]
is there any workaround available to pin comment on a Media? I still experience this when trying to pin a comment.

**Comment by subzeroid** [comment]
Thanks for the reports. This is fixed in #2558.

Root cause: `comment_pin()` / `comment_unpin()` were calling the mobile endpoint without the trailing slash. That can trigger a redirect before the request reaches Instagram, and the redirected request can surface as `405 Method Not Allowed`.

I added regression coverage for the endpoint path and a live upload/comment/pin/unpin test; the live test passed.
