### ISSUE TITLE
[BUG] login error: invalid_parameters

### ISSUE THREAD

**Issue by DGxg9420** [subzeroid/instagrapi#1904]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**
Error returned when logging in using two-factor authentication:
{'message': 'Invalid Parameters', 'status': 'fail', 'error_type': 'invalid_parameters'}

>>> data
'signed_body=SIGNATURE.%7B%22verification_code%22%3A%22713979%22%2C%22phone_id%22%3A%22b78d9618-f9d6-48a7-887e-2711d9414dca%22%2C%22_csrftoken%22%3A%22y8Ps6RjEQFO7GXgM8jqsVfqBHrFk6d1apin8jO0HmCjrwvTkw1kiaWran1DeJP37%22%2C%22two_factor_identifier%22%3Anull%2C%22username%22%3A%22alexandersimmons942%22%2C%22trust_this_device%22%3A%220%22%2C%22guid%22%3A%2294c5445b-a832-4db8-a055-7b5b3a1024b5%22%2C%22device_id%22%3A%22android-8f4e2453fae57a4d%22%2C%22waterfall_id%22%3A%22489d0725-fc76-48d0-b780-6f63b7b42bbe%22%2C%22verification_method%22%3A%223%22%7D'
>>> api_url
'https://i.instagram.com/api/v1/accounts/two_factor_login/'
>>> self.username
'alexandersimmons942'
>>> self.password
'Cwgloqhiqkm244'

**To Reproduce**
cl = Client()
cl.login(username, password, verification_code=twoFactorAuthCode(googleToken))

**Traceback**
Traceback (most recent call last):
  File "E:\python项目\OrderProjects\InsBloggerInfoGather\utils\insLogin.py", line 54, in insLogin
    cl.login(username, password, verification_code=twoFactorAuthCode(googleToken))
  File "E:\python项目\OrderProjects\InsBloggerInfoGather\venv\Lib\site-packages\instagrapi\mixins\auth.py", line 465, in login
    logged = self.private_request(
             ^^^^^^^^^^^^^^^^^^^^^
  File "E:\python项目\OrderProjects\InsBloggerInfoGather\venv\Lib\site-packages\instagrapi\mixins\private.py", line 548, in private_request
    raise e
  File "E:\python项目\OrderProjects\InsBloggerInfoGather\venv\Lib\site-packages\instagrapi\mixins\private.py", line 533, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "E:\python项目\OrderProjects\InsBloggerInfoGather\venv\Lib\site-packages\instagrapi\mixins\private.py", line 455, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: Invalid Parameters

**Desktop (please complete the following information):**
 - OS: win11 23H2
 - Python version python 11.2
 - instagrapi version 2.1.1
 - moveipy version if used
 - imagemagick version if used

**Comment by subzeroid** [comment]
Closing as a duplicate of #1906. This report used the same legacy two-factor invalid_parameters path. Please upgrade to instagrapi 2.7.11 or newer. Also rotate any credentials that were pasted into this public issue.
