### ISSUE TITLE
login not working[BUG]

### ISSUE THREAD

**Issue by MarcoLavoro** [subzeroid/instagrapi#1930]
If I try to execute this:
`>>> from instagrapi import Client

>>> cl = Client()
>>> cl.login(USERNAME, PASSWORD)`

I get this error:

`python prova.py
Status 429: Too many requests
Ignore 429: Continue login
Traceback (most recent call last):
  File "C:\Users\carlo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "C:\Users\carlo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OFFLINEPROJECTS\BOTS\UploadInstagram3\prova.py", line 26, in <module>
    cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
  File "C:\Users\carlo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\auth.py", line 390, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "C:\Users\carlo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 451, in private_request
    raise e
  File "C:\Users\carlo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 438, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\carlo\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\private.py", line 358, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: You'll need to update Instagram to the latest version before you can use the app.
`

Is this a bug?

**Comment by ProgrameurGentil** [comment]
Hi, I'm having the same problem. What do I need to do to solve it?

**Comment by kingbotss** [comment]
Bad IP or Proxy. Change it

**Comment by aboubakrjeb** [comment]
according to the documentation, you can add a delay to mimic the behaviour of a real user:
`# adds a random delay between 1 and 3 seconds after each request
cl.delay_range = [1, 3]`

and you can check if the username exists by sending a get request to `www.instagram.com/{username}` because the `login` function always return true if the credentials are false!!

**Comment by Aniket-k-13** [comment]
✗ Login failed: We can send you an email to help you get back into your account. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server 

am getting a proble while my bot is try to login to insta, is the any solution for this

**Comment by subzeroid** [comment]
Closing as not planned. The 429/rate-limit responses plus update-app/account-recovery login messages are Instagram risk, rate-limit, account, or IP responses, not a deterministic instagrapi bug. Use a clean session, realistic delays, and an IP/device/account state accepted by the official app; if latest instagrapi fails where the official app works from the same environment, open a fresh issue with the exact current response.
