### ISSUE TITLE
[BUG] Empty response message when using `signup`

### ISSUE THREAD

**Issue by brunobely** [subzeroid/instagrapi#1935]
**Describe the bug**
Error `Status 400: Empty response message. Maybe enabled Two-factor auth?` when using the `signup` method to create a new account.

**To Reproduce**
Mostly taken from [`SignUpTestCase`](https://github.com/subzeroid/instagrapi/blob/d1652b15375860efe4a3600a6ad07f3450017604/tests.py#L1246):

```py
  client = Client()
  client.delay_range = [1, 3]
  client.set_proxy('socks5://...')

  # signup() doesn't set device_id but it needs it
  client.device_id = "android-%s" % hashlib.sha256(str(time.time()).encode()).hexdigest()[:16]

  email = 'example@gmail.com'
  display_name = 'John Smith'
  username = 'jsmith123512'
  password = 'can389maw39mxruaj'
  phone_number = '+15559202020'

  user = client.signup(
    username, password, email, phone_number, display_name,
    year=random.randint(1970, 2004),
    month=random.randint(1, 12),
    day=random.randint(1, 28)
  )
```

**Traceback**
```
2024-05-23 11:49:02,420:INFO - https://i.instagram.com/api/v1/consent/get_signup_config/
2024-05-23 11:49:04,130:INFO - None [200] GET https://i.instagram.com/api/v1/consent/get_signup_config/?guid=9c636551-da32-4c5c-9416-9378d5c5fd57&main_account_selected=False (269.0.0.18.75, OnePlus 6T Dev)
2024-05-23 11:49:06,605:INFO - https://i.instagram.com/api/v1/users/check_email/
2024-05-23 11:49:07,580:INFO - None [200] POST https://i.instagram.com/api/v1/users/check_email/ (269.0.0.18.75, OnePlus 6T Dev)
2024-05-23 11:49:10,653:INFO - https://i.instagram.com/api/v1/accounts/send_verify_email/
2024-05-23 11:49:12,275:INFO - None [200] POST https://i.instagram.com/api/v1/accounts/send_verify_email/ (269.0.0.18.75, OnePlus 6T Dev)
Enter code (6 digits) for [redacted] (1): 549160
Enter code "549160" for [redacted] (1 attempts, by 5 seconds)
2024-05-23 11:49:40,619:INFO - https://i.instagram.com/api/v1/accounts/check_confirmation_code/
2024-05-23 11:49:43,393:INFO - None [200] POST https://i.instagram.com/api/v1/accounts/check_confirmation_code/ (269.0.0.18.75, OnePlus 6T Dev)
2024-05-23 11:49:47,801:INFO - https://i.instagram.com/api/v1/accounts/create/
2024-05-23 11:49:48,476:INFO - None [400] POST https://i.instagram.com/api/v1/accounts/create/ (269.0.0.18.75, OnePlus 6T Dev)
2024-05-23 11:49:48,476:ERROR - 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/create/
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_[redacted]/c1a212f4a3cbc7222015ce889f25da32/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/instagram/cli.runfiles/pypi_instagrapi/site-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/private/var/tmp/_bazel_[redacted]/c1a212f4a3cbc7222015ce889f25da32/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/instagram/cli.runfiles/pypi_requests/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/create/
2024-05-23 11:49:48,479:WARNING - Status 400: Empty response message. Maybe enabled Two-factor auth?
Error creating account: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/create/
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6.2
 - Python version: 3.12
 - instagrapi version: 2.1.2

**Comment by zekhoi** [comment]
that because instagrapi add more key when send data (thats what i found), so just remove the unrequired data when sending to endpoint `accounts/create/`

**Comment by zekhoi** [comment]
> that because instagrapi add more key when send data (thats what i found), so just remove the unrequired data when sending to endpoint `accounts/create/`

see https://github.com/subzeroid/instagrapi/pull/1938

**Comment by Altimis** [comment]
the signup method returns Instagram User after account creation : 

```
pk='68663412806' username='Instagram User' full_name='' profile_pic_url=Url('https://instagram.fhex2-1.fna.fbcdn.net/v/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=instagram.fhex2-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=nOPs76iqbjsQ7kNvgGaAit5&edm=AJ9x6zYBAAAA&ccb=7-5&ig_cache_key=YW5vbnltb3VzX3Byb2ZpbGVfcGlj.2-ccb7-5&oh=00_AYCWDUV_axRwc_xMinkPZlq9p_G9oeeUqEN0DVBrvJzIFg&oe=66BC130F&_nc_sid=65462d') profile_pic_url_hd=None is_private=True
```

**Comment by sujay1599** [comment]
Troubleshooting Steps:

	1.	Check for Two-Factor Authentication: Ensure that 2FA is not interfering with the process.
	2.	Switch Proxies: Try using a different proxy or disable it temporarily.
	3.	Wait and Retry: If rate limiting might be the issue, wait for a while before trying again.
	4.	Update the Instagrapi Version: Ensure that the package is up-to-date.
	5.	Check the Data Consistency: Double-check all input data for validity and consistency.
	6.	Use a Different Device ID Generation Strategy: Consider using a more stable and realistic device ID.

If none of these solutions work, you might want to debug further by capturing the exact request and response details to understand better why Instagram is rejecting the request.

**Comment by sujay1599** [comment]
import hashlib
import time
import random
from instagrapi import Client

client = Client()
client.delay_range = [1, 3]

# Optional: Set User-Agent if not handled by Client
client.set_user_agent("Instagram 123.0.0.20.114 Android (28/9; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)")

# Set proxy if necessary
client.set_proxy('socks5://...')

# Generate and set device_id
client.device_id = "android-%s" % hashlib.sha256(str(time.time()).encode()).hexdigest()[:16]

email = 'example@gmail.com'
display_name = 'John Smith'
username = 'jsmith123512'
password = 'can389maw39mxruaj'
phone_number = '+15559202020'

# Encrypt the password if required
encrypted_password = client.password_encrypt(password)

try:
    user = client.signup(
        username, encrypted_password, email, phone_number, display_name,
        year=random.randint(1970, 2004),
        month=random.randint(1, 12),
        day=random.randint(1, 28)
    )
    print("Account created successfully:", user)
except Exception as e:
    print("Error creating account:", e)

**Comment by subzeroid** [comment]
Closing as not planned for the same signup/account-create reason. Empty 400 responses, feedback_required, and suspicious new-account states are Instagram risk checks around modern signup rather than a stable library bug we can fix without a current verified request flow.
