### ISSUE TITLE
[BUG] IP address blocked

### ISSUE THREAD

**Issue by 7FULL** [subzeroid/instagrapi#2037]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**
I run a very simple code and instagram blocks me

**To Reproduce**
First of all I am in europe, and I didnt get it to work until I activated a VPN

This is my code
```
from instagrapi import Client as InstagraClient

instaApi = InstagraClient()
time.sleep(10)
instaApi.login(USERNAME, PASSWORD)
```

**Traceback**
```
Traceback (most recent call last):
  File "I:\$$$\GeneradorImagenes\ImageGeneratorBot\bot\.venv\Lib\site-packages\instagrapi\mixins\private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "I:\$$$\GeneradorImagenes\ImageGeneratorBot\bot\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\$$$\GeneradorImagenes\ImageGeneratorBot\bot\app.py", line 517, in <module>
    instaApi.login(USERNAME, PASSWORD)
  File "I:\$$$\GeneradorImagenes\ImageGeneratorBot\bot\.venv\Lib\site-packages\instagrapi\mixins\auth.py", line 441, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\$$$\GeneradorImagenes\ImageGeneratorBot\bot\.venv\Lib\site-packages\instagrapi\mixins\private.py", line 541, in private_request
    raise e
  File "I:\$$$\GeneradorImagenes\ImageGeneratorBot\bot\.venv\Lib\site-packages\instagrapi\mixins\private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "I:\$$$\GeneradorImagenes\ImageGeneratorBot\bot\.venv\Lib\site-packages\instagrapi\mixins\private.py", line 415, in _send_private_request
    raise BadPassword(**last_json)
instagrapi.exceptions.BadPassword: We can send you an email to help you get back into your account. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server
```

**Expected behavior**
For it to log me in

**Screenshots**
No need for screenshots

**Desktop:**
 - OS: [e.g. Windoes 11]
 - Python version [3.12]
 - instagrapi version [2.1.2]

**Comment by sunmasters** [comment]
Use mobile IP.  Or proxy

**Comment by 7FULL** [comment]
> Use mobile IP. Or proxy

How can I do that?

**Comment by fan9704** [comment]
> Use mobile IP. Or proxy

How can I do that?

**Comment by Zersya** [comment]
> Use mobile IP. Or proxy

I've tried both residential and mobile proxies, yet the "BadPassword" exception persists.

**Comment by subzeroid** [comment]
Closing this as account/network risk behavior rather than an instagrapi code bug. The server response says Instagram is rejecting the login because of IP/account trust state. instagrapi cannot make a blocked IP/session trusted; use stable account-specific sessions, avoid repeated fresh password logins, and keep device/proxy identity consistent. For supported business integrations, use Meta Instagram Platform APIs where they cover the use case: https://developers.facebook.com/docs/instagram-platform/. For data retrieval at scale, a hosted API layer can avoid maintaining private API sessions; one option is HikerAPI (trial with 100 free requests): https://hikerapi.com/p/fyfx6ygs
