### ISSUE TITLE
[BUG] Video is not being sent to direct.

### ISSUE THREAD

**Issue by Anton-Euro** [subzeroid/instagrapi#2054]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**
When I try to send a video to direct, it gives an error:
`instagrapi.exceptions.UnknownError: This feature is no longer supported.`

**To Reproduce**
```python
from instagrapi import Client

cl = Client()
cl.login("login", "password")

cl.direct_send_video("path/to/video", user_ids=[user_id])
```

**Traceback**
```bash
Traceback (most recent call last):
  File "/Users/geml/python/semily_consulting/.venv/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/Users/geml/python/semily_consulting/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/direct_v2/threads/broadcast/configure_video/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geml/python/semily_consulting/instagram_bot/test.py", line 6, in <module>
    cl.direct_send_video("/Users/geml/Desktop/cTZgi4Foyuc0Kahm.mp4", user_ids=[70576365517])
  File "/Users/geml/python/semily_consulting/.venv/lib/python3.12/site-packages/instagrapi/mixins/direct.py", line 502, in direct_send_video
    return self.direct_send_file(path, user_ids, thread_ids, content_type="video")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/geml/python/semily_consulting/.venv/lib/python3.12/site-packages/instagrapi/mixins/direct.py", line 575, in direct_send_file
    result = self.private_request(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/geml/python/semily_consulting/.venv/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 541, in private_request
    raise e
  File "/Users/geml/python/semily_consulting/.venv/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/Users/geml/python/semily_consulting/.venv/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 448, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: This feature is no longer supported.
```

**Desktop:**
 - OS: MacOS Sequoia
 - Python version 3.12.7
 - instagrapi version latest
 - moveipy version 1.0.3

**Comment by ShashiTharoor** [comment]
was it working before?

**Comment by MohammadNasrIsfahany** [comment]
I have this problem too.

**Comment by mnproduction** [comment]
Same issue

**Comment by Cipherism** [comment]
did anyone fix it ?

**Comment by steffyjk** [comment]
@Anton-Euro Any Updates on this ?

**Comment by subzeroid** [comment]
Related fix landed in c564a68.

What changed:
- `direct_send_video()` no longer calls the deprecated `direct_v2/threads/broadcast/configure_video/` path that was returning `This feature is no longer supported`
- it now routes DM video sends through the existing `video_upload_to_direct(...)` flow instead
- when called with `user_ids`, it first resolves an existing direct thread; if none exists, it now raises a clear `DirectThreadNotFound` instead of surfacing the old server-side dead endpoint error

Regression coverage added in `tests.DirectMixinRegressionTestCase`, verified with:
- `.venv/bin/python -m unittest tests.DirectMixinRegressionTestCase`

No fresh live verification yet, so I am not auto-closing this one yet.

**Comment by subzeroid** [comment]
Closing now. The deprecated direct_v2/threads/broadcast/configure_video/ path from this traceback has been replaced. Relevant fixes: https://github.com/subzeroid/instagrapi/commit/c564a68 and https://github.com/subzeroid/instagrapi/commit/9e226a598bb25c870aaa23ab2b6aae6180232b5d, with follow-ups https://github.com/subzeroid/instagrapi/commit/c0284ab7c60a10291a4f83762f3c0521583a8728 and https://github.com/subzeroid/instagrapi/commit/c92be79. Direct video send has since been covered by regression tests and live direct media checks for both thread_ids and user_ids. If the latest version still fails, please open a new issue with the new traceback and video metadata.
