### ISSUE TITLE
Error while importing Client

### ISSUE THREAD

**Issue by YashIndane** [subzeroid/instagrapi#2057]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Description**
Running the very first line -> from instagrapi import Client, gives this error ->

**To Reproduce**
 `from instagrapi import Client
`
**Traceback**'

Traceback (most recent call last):
  File ".\insta.py", line 1, in <module>
    from instagrapi import Client
  File "C:\Users\YASH\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\__init__.py", line 7, in <module>
    from instagrapi.mixins.account import AccountMixin
  File "C:\Users\YASH\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\account.py", line 8, in <module>
    from instagrapi.extractors import extract_account, extract_user_short
  File "C:\Users\YASH\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\extractors.py", line 6, in <module>
    from .types import (
  File "C:\Users\YASH\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\types.py", line 130, in <module>
    class Media(BaseModel):
  File "C:\Users\YASH\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\types.py", line 131, in Media
    pk: str | int
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Expected behavior**
It should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version: 3.8.2
 - instagrapi version: latest
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by subzeroid** [comment]
This is no longer an open bug on current master; it is an unsupported runtime version case.

Current package metadata explicitly requires Python 3.9+: https://github.com/subzeroid/instagrapi/blob/master/pyproject.toml#L30

So the Python 3.8 traceback in this report is expected for modern releases and is not something I am going to treat as a current bug.

For reference, current master does support Python 3.9 again, and that was recently verified in a real python:3.9 container. But Python 3.8 is outside the declared support range.
